import Head from "next/head";
import Image from "next/image";
import Graph from "../src/components/Graph";

export default function Home() {
  return (
    <>
      <Head>
        <title>LLM Axis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/drag.png" />
      </Head>
      <main className="leading-tight">
        <Graph />
        <a
          href="https://www.trudy.computer/projects/llm-axis"
          className="absolute bottom-2 left-2 border-black border-[1px] p-2 hover:bg-gray-100"
        >
          ⓘ More about this experiment
        </a>
      </main>
    </>
  );
}
